---
title: "Week 3"
output: 
  html_document: 
    highlight: pygments
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Connect h2o

```{r, message = FALSE}
library(h2o)
library(tidyverse)
library(magrittr)
h2o.init()
h2o.no_progress()
```


## GLM

```{r}


data <- read_table('https://data.princeton.edu/wws509/datasets/smoking.dat')
data <- data %>% select(-X1) %>% mutate(prop = floor(dead/pop*1000))
data <- as.h2o(data)
data$age %<>% as.factor()
data$smoke %<>% as.factor

summary(data)
str(data)
x <- 1:2
y <- 5

mGLM <- h2o.glm(x, y, data,
                family = 'poisson',
                model_id = 'smoking_p')

mGLM
```


## Naive Bayes

```{r}
h2o.iris <- as.h2o(iris)
parts <- h2o.splitFrame(h2o.iris, 0.8)

train <- parts[[1]]
test <- parts[[2]]

mNB <- h2o.naiveBayes(1:4, 5, train)
mNB

h2o.performance(mNB, test)
```


## Grid Search

```{r}
mGLM2 <- h2o.grid('glm', x = x, y = y, training_frame = data,
                family = 'poisson',
                search_criteria = list(
                  strategy = 'Cartesian'
                ),
                hyper_params = list(
                  alpha = c(0.1, 0.25, 0.5, 0.75)
                ),
                lambda_search = TRUE)

h2o.getModel(mGLM2@model_ids[[1]])
```

## Disconnect

```{r}
h2o.shutdown(prompt = FALSE)
```