---
title: "Week 5"
output: 
  html_document: 
    highlight: pygments
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Connect h2o

```{r connect, message = FALSE}
library(h2o)
library(tidyverse)
library(magrittr)
h2o.init()
h2o.no_progress()
```

## Autoencoder

```{r}
iris.h2o <- as.h2o(iris)
parts <- h2o.splitFrame(iris.h2o, ratios = 0.8)
parts[[1]] -> train
parts[[2]] -> test

nrow(train)


mAE_5_3_5 <- h2o.deeplearning(x = 1:5, training_frame = train,
                        autoencoder = TRUE, epochs = 300,
                        model_id = 'mAE_5_3_5',
                        train_samples_per_iteration = nrow(train),
                        score_interval = 0,
                        score_duty_cycle = 1.0,
                        hidden = c(5, 3, 5),
                        activation = 'Tanh')

h2o.scoreHistory(mAE_5_3_5)

h2o.predict(mAE_5_3_5, test) %>% head %>% select(5:8)

test %>% head %>% select(1:4)

```

## PCA

```{r}
m_PCA <- h2o.prcomp(train, 1:4, k = 4, impute_missing = TRUE)
m_PCA

train_df <- train %>% as.data.frame
p <- h2o.predict(m_PCA, train) %>% as.data.frame
p <- p %>% mutate(Species = train_df$Species)

ggplot(p, aes(x = PC1, y = PC2, color = Species)) + geom_point()

```


## GLRM

```{r}
mGLRM <- h2o.glrm(train, 1:5, k = 2)
mGLRM

mean(h2o.predict(mGLRM, test)[, 5] == test$Species)

```
 