---
title: "Week 6"
output: 
  html_document: 
    highlight: pygments
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Connect h2o

```{r connect, message = FALSE}
library(h2o)
library(tidyverse)
library(lubridate)
library(magrittr)

h2o.init()
h2o.no_progress()
```



## Get Data

```{r}
# url <- 'http://coursera.h2o.ai/house_data.3487.csv'
# house <- read_csv(url)
# write_csv(house, './temp/house.csv')

house <- read_csv('./temp/house.csv') 

house_cleaned <- house %>% select(-id) %>% mutate(year = year(date), month = month(date), day = day(date)) %>% select(-date)

house_h2o <- as.h2o(house_cleaned)

parts_h2o <- h2o.splitFrame(house_h2o, 0.9, seed = 123)

train_h2o <- parts_h2o[[1]]
test_h2o <- parts_h2o[[2]]

nrow(train_h2o)
nrow(test_h2o)
```

## Develop Models

```{r}
y <- 1
x <- 2:22

# m_glm_base <-
#   h2o.glm(
#     x = x,
#     y = y,
#     training_frame = train_h2o,
#     model_id = 'base_glm',
#     seed = 123,
#     family = 'gaussian',
#     nfolds = 5,
#     fold_assignment = "Modulo",
#     keep_cross_validation_predictions = TRUE
#   )
# 
# h2o.performance(m_glm_base, test_h2o) # 360908.6

# m_glm_lasso <- h2o.glm(
#   x = x,
#   y = y,
#   training_frame = train_h2o,
#   seed = 123,
#   family = 'gaussian',
#   alpha = 1,
#   lambda_search = TRUE,
#   nfolds = 5,
#   fold_assignment = "Modulo",
#   keep_cross_validation_predictions = TRUE
# )
# 
# h2o.performance(m_glm_lasso, test_h2o) # 194171.3

m_xgb_base <- h2o.xgboost(
  x = x,
  y = y,
  training_frame = train_h2o,
  seed = 123,
  nfolds = 5,
  fold_assignment = "Modulo",
  keep_cross_validation_predictions = TRUE
)

h2o.performance(m_xgb_base, test_h2o) # 122499.4


m_gbm_base <- h2o.gbm(
  x = x,
  y = y,
  training_frame = train_h2o,
  seed = 123,
  nfolds = 5,
  fold_assignment = "Modulo",
  keep_cross_validation_predictions = TRUE
)

h2o.performance(m_gbm_base, test_h2o) ## 123969.1

ids <- c(m_gbm_base@model_id, m_xgb_base@model_id)

m_se <- h2o.stackedEnsemble(
  x = x,
  y = y,
  training_frame = train_h2o,
  base_models = c(m_gbm_base@model_id, m_xgb_base@model_id)
)

h2o.performance(m_se, test_h2o) ## 362749

# H2ORegressionMetrics: stackedensemble
# 
# MSE:  131586803632
# RMSE:  362749
# MAE:  237071.6
# RMSLE:  0.5529791
# Mean Residual Deviance :  131586803632




# h2o.saveModel(m_gbm_base, './')
# h2o.saveModel(m_xgb_base, './')
# h2o.saveModel(m_se, "./")
```

























